# Generated by Django 4.0.4 on 2022-07-07 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='メール')),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='挨拶文')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/', verbose_name='画像')),
                ('social_github', models.CharField(blank=True, max_length=200, null=True, verbose_name='Github')),
                ('social_website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
