# Generated by Django 4.0.4 on 2022-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='assets/img/profiles/user-default.png', null=True, upload_to='assets/img/profiles/', verbose_name='画像'),
        ),
    ]
