# Generated by Django 4.0.5 on 2022-07-02 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True, verbose_name='感想（記述）')),
                ('value', models.CharField(blank=True, choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, verbose_name='感想（選択）')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.app')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sites.tag'),
        ),
    ]
