# Generated by Django 4.0.4 on 2022-07-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_tag_app_vote_ratio_app_vote_total_review_app_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Site',
        ),
    ]
