# Generated by Django 4.0.4 on 2022-07-03 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_rename_app_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='app',
            new_name='site',
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('Excellent', '大変有意義'), ('Good', '参考になる'), ('OK', '見る価値あり'), ('Bad', '良くない')], max_length=200, verbose_name='感想（選択）'),
        ),
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.category'),
        ),
    ]
