# Generated by Django 4.0.4 on 2022-07-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_category_rename_app_review_site_alter_review_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sites.tag', verbose_name='タグ'),
        ),
    ]
