# Generated by Django 4.0.4 on 2022-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('up', '参考になる'), ('down', 'いまいち')], max_length=200, verbose_name='感想（選択）'),
        ),
    ]
